### ISSUE TITLE
[FEATURE] Write sql-query for creating table "party"

### ISSUE THREAD

**Issue by Havryliuk-Vasyl** [Havryliuk-Vasyl/asd-java-intern#31]
**Feature description**
Check this sql-query for creating table "party" and execute it:
`CREATE TABLE party (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    state VARCHAR(15) NOT NULL DEFAULT 'Initial',
    postal_address VARCHAR(500) NULL DEFAULT NULL,
    email_address VARCHAR(100) NULL DEFAULT NULL,
    mobile_phone VARCHAR(30) NULL DEFAULT NULL,
    password VARCHAR(255) NULL DEFAULT NULL,
    currency VARCHAR(3) NULL DEFAULT NULL,
    user_type VARCHAR(15) NULL DEFAULT NULL,
    version TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
`

**Expected result**
Checked sql-query for creating table "party" and executed it

**Comment by rdovgan** [comment]
No 😌
**You** should write a create query for creating table `party`. I will only check and execute it

**Comment by rdovgan** [comment]
Processed next script:
```mysql
CREATE TABLE party
(
	id             INT          NOT NULL AUTO_INCREMENT,
	name           VARCHAR(45)  NOT NULL,
	state          VARCHAR(15)  NOT NULL DEFAULT 'Initial',
	postal_address VARCHAR(500) NULL     DEFAULT NULL,
	email_address  VARCHAR(100) NULL     DEFAULT NULL,
	mobile_phone   VARCHAR(30)  NULL     DEFAULT NULL,
	password       VARCHAR(255) NULL     DEFAULT NULL,
	currency       VARCHAR(3)   NULL     DEFAULT NULL,
	user_type      VARCHAR(15)  NULL     DEFAULT NULL,
	version        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
```
