### ISSUE TITLE
[FEATURE] Check and execute sql-query for creating table "channel_partner"

### ISSUE THREAD

**Issue by Havryliuk-Vasyl** [Havryliuk-Vasyl/asd-java-intern#34]
**Feature description**
Check this sql-query for creating table "channel_partner" and execute it:
`CREATE TABLE channel_partner ( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, party_id INT NOT NULL, abbreviation VARCHAR(6) NOT NULL, channel_name VARCHAR(45) NOT NULL, state CHAR(15) NOT NULL DEFAULT 'Created', commission DOUBLE DEFAULT NULL, bp_commission DOUBLE NOT NULL DEFAULT 3.0, funds_holder TINYINT NOT NULL DEFAULT 0, version TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);`

**Expected result**
Checked sql-query for creating table "channel_partner" and executed it

**Comment by oleksandrtytkoasd** [comment]
```sql
CREATE TABLE channel_partner
(
    id            INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    party_id      INT         NOT NULL,
    abbreviation  VARCHAR(6)  NOT NULL,
    channel_name  VARCHAR(45) NOT NULL,
    state         CHAR(15)    NOT NULL DEFAULT 'Created',
    commission    DOUBLE               DEFAULT NULL,
    bp_commission DOUBLE      NOT NULL DEFAULT 3.0,
    funds_holder  TINYINT     NOT NULL DEFAULT 0,
    version       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
```
@Havryliuk-Vasyl Table was created
